### ISSUE TITLE
About roadmap

### ISSUE THREAD

**Issue by sneko** [OscarYuen/go-graphql-starter#14]
Hi @OscarYuen!

I saw you've these goals on the roadmap:
- Support subscription
- Support web-socket notification and messaging

Could you tell me if you are currently working on that please 😃 ?

I'm just discovering GraphQL in Golang instead of JS and it would be great to use streams 👍 

Thank you

**Comment by OscarYuen** [comment]
Hello @sneko ,

Thanks for your enquiry 😃

I am currently working on the company project with this backend. For web socket, I created a little branch called web-socket before to do some basic experiment. It works very well for web-socket based messaging. But it is not fully integrated into the main branch yet.
For subscription, I would keep an eye on graphql-go library to see if there is any progress. So far the subscription function is not supported by graphql-go yet.

Thanks
