### ISSUE TITLE
hasNextPage Logic

### ISSUE THREAD

**Issue by riyan10dec** [OscarYuen/go-graphql-starter#16]
Hi OscarYuen, 
on your user_connection_resolver.go on func PageInfo you have function like this:
`func (r *usersConnectionResolver) PageInfo() *pageInfoResolver {
	return &pageInfoResolver{
		startCursor: service.EncodeCursor(r.from),
		endCursor:   service.EncodeCursor(r.to),
		hasNextPage: false,
	}
}`
It seems hasNextPage is always false. how is the logic to provide real hasNextPage value?
Thanks.

**Comment by OscarYuen** [comment]
@riyan10dec 

In this starter, the hasNextPage value is for demo purpose.
In my production case, I need to pass the boolean value to its resolver in query/mutation.

For example, at the end of my go function for graphql query of getting book list
```
       ....
       ....
	books, isLastPage, err := ctx.Value("bookService").(* bookService).List(db, args.First, args.Before, args.After) // db is the db connector, args is the argument from graphql endpoint
	return &booksConnectionResolver{books: books, from: &(books[0].ID), to: &(books[len(books)-1].ID), hasNextPage: !isLastPage}, err
	}

```
By this method, you can even pass totalCount, isPreviousPage to resolver. It depends on your need.
