### ISSUE TITLE
go build server.go error

### ISSUE THREAD

**Issue by mattdinhnguyen** [OscarYuen/go-graphql-starter#18]
$ go generate ./schema
$ go build server.go
# github.com/OscarYuen/go-graphql-starter/loader
loader/user.go:17:21: cannot use userLoader literal.loadBatch (type func("golang.org/x/net/context".Context, dataloader.Keys) []*dataloader.Result) as type dataloader.BatchFunc in return argument

Please advise fix

**Comment by OscarYuen** [comment]
@mattdinhnguyen 
Sorry for late reply due to recent busy work.
I would take a look on it. Thanks for reporting

**Comment by mattdinhnguyen** [comment]
@OscarYuen I only got this error on my MAC OS, I don't have this error on ubuntu 16.04

**Comment by hanorine** [comment]
I am not having this issue on MacOS. You can close this issue unless @mattdinhnguyen still has this problem?
